[build]
  command = "echo 'No build step needed for Netlify Functions'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Function configuration
[functions]
  node_bundler = "esbuild"

# Redirects for API endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# CORS headers for API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"

# Environment variables (set these in Netlify dashboard)
# REPLICATE_API_TOKEN = "YOUR_REPLICATE_API_TOKEN_HERE"
